### ISSUE TITLE
Crawl dashboards in crawl template

### ISSUE THREAD

**Issue by chdoig** [memex-explorer/memex-explorer#170]
Some found issues from testing PR #158:

- [ ] Problem with large csv files in ACHE crawls (actions tracked in #171 —@kdodia)

- [ ] Problem initializing when ACHE data is empty (#173 —@kdodia)

ache-test
```
Traceback (most recent call last):
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdoig/work/test_memex/memex-explorer/app/views.py", line 261, in crawl
    scripts, divs = default_ache_dash(project, crawl)
  File "/Users/cdoig/work/test_memex/memex-explorer/app/plotting.py", line 74, in default_ache_dash
    domain_script, domain_div = domain.create()
  File "/Users/cdoig/work/test_memex/memex-explorer/app/viz/domain.py", line 69, in create
    self.source = self.update_source()
  File "/Users/cdoig/work/test_memex/memex-explorer/app/viz/domain.py", line 55, in update_source
    df.columns = ['relevant', 'crawled', 'frontier']
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/pandas/core/generic.py", line 1958, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/src/properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas/lib.c:41295)
    
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/pandas/core/generic.py", line 406, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/pandas/core/internals.py", line 2217, in set_axis
    'new values have %d elements' % (old_len, new_len))
ValueError: Length mismatch: Expected axis has 1 elements, new values have 3 elements
```

ache-es
```
Traceback (most recent call last):
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cdoig/work/test_memex/memex-explorer/app/views.py", line 257, in crawl
    scripts, divs = default_ache_dash(project, crawl)
  File "/Users/cdoig/work/test_memex/memex-explorer/app/plotting.py", line 74, in default_ache_dash
    domain_script, domain_div = domain.create()
  File "/Users/cdoig/work/test_memex/memex-explorer/app/viz/domain.py", line 69, in create
    self.source = self.update_source()
  File "/Users/cdoig/work/test_memex/memex-explorer/app/viz/domain.py", line 51, in update_source
    df['domain'] = df['url'].apply(partial(get_tld, fail_silently=True))
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/pandas/core/series.py", line 2058, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/src/inference.pyx", line 1046, in pandas.lib.map_infer (pandas/lib.c:56997)
    
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/site-packages/tld/utils.py", line 149, in get_tld
    domain_name = urlparse(url).netloc.split(":", 1)[0]
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/Users/cdoig/anaconda/envs/memex/lib/python2.7/urlparse.py", line 191, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by brittainhard** [comment]
This issue pertains to the Flask app, but I'm keeping it open in case it becomes a problem for the Django app.

**Comment by brittainhard** [comment]
These issues have been fixed in the Django version.
