### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#260]
This has been happening on both @kdodia's machine and mine when we have a nutch crawl page open. Not too sure what it means, @quasiben and @chdoig, would you guys have any idea whats going on?
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53485)
Traceback (most recent call last):
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/SocketServer.py", line 653, in __init__
    self.finish()
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/Users/brittainchristopherhard/anaconda/envs/memex/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by brittainhard** [comment]
No longer an issue for the Django version.
