### ISSUE TITLE
Unable to crawl using Docker image

### ISSUE THREAD

**Issue by chrismattmann** [memex-explorer/memex-explorer#267]
So i downloaded the docker image and built/ran it
Here is the use case
1. Create Nutch Project
2. Create Nutch crawl
3. add default seed file with 1 line (foo.txt) and upload
http://sunset.usc.edu/~mattmann/
4. Crawl is created
5. Press start button

Receive:

```
Traceback (most recent call last):
  File "/root/memex-explorer/app/views.py", line 344, in run_crawl
    pid = crawl_instance.start()
  File "/root/memex-explorer/app/crawls.py", line 157, in start
    self.proc = Popen(['crawl', self.seed_dir, self.crawl_dir, str(self.number_of_rounds)])
  File "/root/anaconda/envs/memex-explorer/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/root/anaconda/envs/memex-explorer/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jeffbaumes** [comment]
I am able to replicate this issue after installing with `boot2docker` `dmg` installer on Mac. Same error.

**Comment by kdodia** [comment]
@chdoig, should try to reproduce this with the latest configuration.

**Comment by brittainhard** [comment]
Old issue.
