### ISSUE TITLE
Ache Crawl Bug

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#357]
Here's the traceback. It looks like ache is having trouble initiating whatever storage it is using.

```
>>>>>URL:http://www.gaatw.org/index.php?option=com_content&view=article&id=745:isd-promoting-violence-free-lives-for-women&catid=95:member-profile&Itemid=67 REL:2
>>>RELEV:299.0
www
LOG>crawler_group_3_0>selectUrl() linkServer end(2):http://www.gaatw.org/index.php?option=com_content&view=article&id=745:isd-promoting-violence-free-lives-for-women&catid=95:member-profile&Itemid=67
LOG>crawler_group_3_0>update() linkStorage end(1424816150820)
crawler_group_3_0>after request url
crawler_group_3_0>after check url
crawler_group_3_0>after download data
crawler_group_3_0>after process data
crawler_group_3_0>after check data
R>crawler_group_3_0 send page with http://www.gaatw.org/index.php?option=com_content&view=article&id=745:isd-promoting-violence-free-lives-for-women&catid=95:member-profile&Itemid=67 to TargetStorage .
Erro de comunicacao: Connection refused
Dormindo 5 mls
[24/FEB/2015:22:15:51] [SocketAdapterFactory] [produce] [localhost:1987]
Erro de comunicacao: Connection refused
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.getSocket(StorageRemoteAdapter.java:78)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.defaultMethod(StorageRemoteAdapter.java:180)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.insert(StorageRemoteAdapter.java:272)
	at focusedCrawler.util.storage.distribution.StorageRemoteAdapterReconnect.insert(StorageRemoteAdapterReconnect.java:183)
	at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:377)
	at focusedCrawler.crawler.Crawler.run(Crawler.java:313)
--
focusedCrawler.util.distribution.CommunicationException: Connection refused
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.defaultMethod(StorageRemoteAdapter.java:240)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.insert(StorageRemoteAdapter.java:272)
	at focusedCrawler.util.storage.distribution.StorageRemoteAdapterReconnect.insert(StorageRemoteAdapterReconnect.java:183)
	at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:377)
	at focusedCrawler.crawler.Crawler.run(Crawler.java:313)
crawler_group_3_0:Connection refused
focusedCrawler.crawler.CrawlerException: crawler_group_3_0:Connection refused
	at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:389)
	at focusedCrawler.crawler.Crawler.run(Crawler.java:313)
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.getSocket(StorageRemoteAdapter.java:78)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.defaultMethod(StorageRemoteAdapter.java:180)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.insert(StorageRemoteAdapter.java:272)
	at focusedCrawler.util.storage.distribution.StorageRemoteAdapterReconnect.insert(StorageRemoteAdapterReconnect.java:183)
	at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:377)
	at focusedCrawler.crawler.Crawler.run(Crawler.java:313)
--
focusedCrawler.util.distribution.CommunicationException: Connection refused
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.defaultMethod(StorageRemoteAdapter.java:240)
	at focusedCrawler.util.storage.socket.StorageRemoteAdapter.insert(StorageRemoteAdapter.java:272)
	at focusedCrawler.util.storage.distribution.StorageRemoteAdapterReconnect.insert(StorageRemoteAdapterReconnect.java:183)
	at focusedCrawler.crawler.CrawlerImpl.sendData(CrawlerImpl.java:377)
	at focusedCrawler.crawler.Crawler.run(Crawler.java:313)
```

**Comment by gadgetlabs** [comment]
How did you fix this?

**Comment by brittainhard** [comment]
Going to close this. We managed to solve the problem by deploying our application to another server. We were unable to re-create any of the bugs, or figure out where they were coming from.
