### ISSUE TITLE
Vagrantfile/Salt - celery workers not quite working right

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#525]
debug output
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/source$ /home/vagrant/miniconda/envs/memex/bin/python -m celery worker -A memex --pidfile=celeryd.pid -l debug
[2015-05-22 22:21:59,203: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2015-05-22 22:21:59,208: DEBUG/MainProcess] | Worker: Building graph...
[2015-05-22 22:21:59,209: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Queues (intra), Pool, Autoscaler, StateDB, Beat, Autoreloader, Consumer}
[2015-05-22 22:21:59,214: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2015-05-22 22:21:59,215: DEBUG/MainProcess] | Consumer: Building graph...
[2015-05-22 22:21:59,223: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Agent, Gossip, Heart, event loop}

 -------------- celery@vagrant-ubuntu-trusty-64 v3.1.18 (Cipater)
---- **** -----
--- * ***  * -- Linux-3.13.0-51-generic-x86_64-with-debian-jessie-sid
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         memex:0x7f3c50384910
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery


[tasks]
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . memex.celery.debug_task
  . task_manager.crawl_tasks.ache
  . task_manager.crawl_tasks.nutch
  . task_manager.docker_tasks.start_containers
  . task_manager.file_tasks.unzip
  . task_manager.tika_tasks.create_index

[2015-05-22 22:21:59,233: DEBUG/MainProcess] | Worker: Starting Hub
[2015-05-22 22:21:59,234: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:21:59,234: DEBUG/MainProcess] | Worker: Starting Pool
[2015-05-22 22:21:59,241: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:21:59,242: DEBUG/MainProcess] | Worker: Starting Consumer
[2015-05-22 22:21:59,242: DEBUG/MainProcess] | Consumer: Starting Connection
[2015-05-22 22:21:59,254: INFO/MainProcess] Connected to redis://localhost:6379//
[2015-05-22 22:21:59,255: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:21:59,255: DEBUG/MainProcess] | Consumer: Starting Events
[2015-05-22 22:21:59,262: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:21:59,262: DEBUG/MainProcess] | Consumer: Starting Mingle
[2015-05-22 22:21:59,263: INFO/MainProcess] mingle: searching for neighbors
[2015-05-22 22:22:00,267: INFO/MainProcess] mingle: all alone
[2015-05-22 22:22:00,267: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:22:00,267: DEBUG/MainProcess] | Consumer: Starting Tasks
[2015-05-22 22:22:00,271: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:22:00,271: DEBUG/MainProcess] | Consumer: Starting Control
[2015-05-22 22:22:00,273: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:22:00,273: DEBUG/MainProcess] | Consumer: Starting Gossip
[2015-05-22 22:22:00,275: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:22:00,275: DEBUG/MainProcess] | Consumer: Starting Heart
[2015-05-22 22:22:00,276: DEBUG/MainProcess] ^-- substep ok
[2015-05-22 22:22:00,276: DEBUG/MainProcess] | Consumer: Starting event loop
/home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2015-05-22 22:22:00,277: WARNING/MainProcess] /home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/celery/fixups/django.py:265: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2015-05-22 22:22:00,279: WARNING/MainProcess] celery@vagrant-ubuntu-trusty-64 ready.
[2015-05-22 22:22:00,279: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2015-05-22 22:22:00,280: DEBUG/MainProcess] basic.qos: prefetch_count->4
[2015-05-22 22:22:11,843: INFO/MainProcess] Received task: task_manager.crawl_tasks.nutch[6e7088cb-e527-44dd-a083-5bc14c5b011d]
[2015-05-22 22:22:11,844: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f3c50059500> (args:('task_manager.crawl_tasks.nutch', '6e7088cb-e527-44dd-a083-5bc14c5b011d', (<Crawl: mm>,), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (<Crawl: mm>,), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': u'celery', u'exchange': u'celery'}, 'expires': None, u'hostname': 'celery@vagrant-ubuntu-trusty-64', 'task': 'task_manager.crawl_tasks.nutch', 'callbacks': None, u'correlation_id': u'6e7088cb-e527-44dd-a083-5bc14c5b011d', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'db2d8957-7b72-3509-afda-2cf0f144e1cd', 'id': '6e7088cb-e527-44dd-a083-5bc14c5b011d', u'headers': {}}) kwargs:{})
[2015-05-22 22:22:11,848: DEBUG/MainProcess] Task accepted: task_manager.crawl_tasks.nutch[6e7088cb-e527-44dd-a083-5bc14c5b011d] pid:17755
[2015-05-22 22:22:11,860: DEBUG/Worker-1] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[2015-05-22 22:22:11,876: DEBUG/Worker-1] (0.014) QUERY = u'INSERT INTO "task_manager_crawltask" ("pid", "crawl_id", "uuid") VALUES (%s, %s, %s)' - PARAMS = (17760, 3, u'6e7088cb-e527-44dd-a083-5bc14c5b011d'); args=[17760, 3, '6e7088cb-e527-44dd-a083-5bc14c5b011d']
[2015-05-22 22:22:11,894: DEBUG/Worker-1] (0.001) QUERY = u'SELECT "crawl_space_crawl"."id", "crawl_space_crawl"."name", "crawl_space_crawl"."slug", "crawl_space_crawl"."description", "crawl_space_crawl"."crawler", "crawl_space_crawl"."status", "crawl_space_crawl"."config", "crawl_space_crawl"."seeds_list", "crawl_space_crawl"."pages_crawled", "crawl_space_crawl"."harvest_rate", "crawl_space_crawl"."project_id", "crawl_space_crawl"."crawl_model_id", "crawl_space_crawl"."location", "crawl_space_crawl"."rounds_left" FROM "crawl_space_crawl" WHERE "crawl_space_crawl"."id" = %s LIMIT 21' - PARAMS = (3,); args=(3,)
[2015-05-22 22:22:11,895: DEBUG/Worker-1] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[2015-05-22 22:22:11,900: DEBUG/Worker-1] (0.004) QUERY = u'UPDATE "crawl_space_crawl" SET "name" = %s, "slug" = %s, "description" = %s, "crawler" = %s, "status" = %s, "config" = %s, "seeds_list" = %s, "pages_crawled" = %s, "harvest_rate" = %s, "project_id" = %s, "crawl_model_id" = NULL, "location" = %s, "rounds_left" = %s WHERE "crawl_space_crawl"."id" = %s' - PARAMS = (u'mm', u'mm', u'nny', u'nutch', u'STARTING', u'config_default', u'/vagrant/source/resources/crawls/mm/seeds', 0, 0.0, 1, u'/vagrant/source/resources/crawls/mm', 0, 3); args=(u'mm', u'mm', u'nny', u'nutch', u'STARTING', u'config_default', u'/vagrant/source/resources/crawls/mm/seeds', 0, 0.0, 1, u'/vagrant/source/resources/crawls/mm', 0, 3)
[2015-05-22 22:22:11,904: INFO/MainProcess] Task task_manager.crawl_tasks.nutch[6e7088cb-e527-44dd-a083-5bc14c5b011d] succeeded in 0.0585073550028s: 'Round Complete'
```

**Comment by ahmadia** [comment]
Things we've discovered:

* Right now the "salt"-launched celery is not behaving correctly, but it works if we launch from a logged in ssh.

* The "nutch" does not work because there is no system Java installed.  We may need to export a variable that correctly points to the Java install.

cc: @lewismc

**Comment by ahmadia** [comment]
any jdk will get nutch going:     export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/"

**Comment by lewismc** [comment]
To add. Any JDK 1.7 and above.


On Friday, May 22, 2015, Aron Ahmadia <notifications@github.com> wrote:

> any jdk will get nutch going: export
> JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/525#issuecomment-104807737>
> .
>


-- 
*Lewis*

**Comment by ahmadia** [comment]
```
JAVA_HOME is set to '/usr/lib/jvm/java-7-openjdk-amd64/'
~/miniconda/envs/memex/lib/nutch /vagrant/source
Injecting seed URLs
/home/vagrant/miniconda/envs/memex/lib/nutch/bin/nutch inject /vagrant/source/resources/crawls/r/seeds/crawldb --index
Injector: starting at 2015-05-23 03:55:14
Injector: crawlDb: /vagrant/source/resources/crawls/r/seeds/crawldb
Injector: urlDir: --index
Injector: Converting injected urls to crawl db entries.
Injector: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/home/vagrant/miniconda/envs/memex/lib/nutch/--index
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:197)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:208)
	at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1081)
	at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1073)
	at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:910)
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1353)
	at org.apache.nutch.crawl.Injector.inject(Injector.java:324)
	at org.apache.nutch.crawl.Injector.run(Injector.java:380)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.nutch.crawl.Injector.main(Injector.java:370)

Error running:
  /home/vagrant/miniconda/envs/memex/lib/nutch/bin/nutch inject /vagrant/source/resources/crawls/r/seeds/crawldb --index
Failed with exit value 255.
/vagrant/source
```

@brittainhard - is this possibly a problem with your seed list injector?

**Comment by ahmadia** [comment]
Nope, I can get this error with either an "uploaded" seed file or running from the command line.

**Comment by lewismc** [comment]
The parameter for the injector job is incorrect, your argument is --Index
This does not exist

On Friday, May 22, 2015, Aron Ahmadia <notifications@github.com> wrote:

> Nope, I can get this error with either an "uploaded" seed file or running
> from the command line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/memex-explorer/memex-explorer/issues/525#issuecomment-104829888>
> .
>


-- 
*Lewis*

**Comment by ahmadia** [comment]
I'm also seeing this error in the Django logs, I think it may be related.

```
: Traceback (most recent call last):
==> default:   File "/home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
==> default:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
==> default:   File "/home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
==> default:     return self.dispatch(request, *args, **kwargs)
==> default:   File "/home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
==> default:     return handler(request, *args, **kwargs)
==> default:   File "/vagrant/source/apps/crawl_space/views.py", line 80, in post
==> default:     crawl_object = self.get_object()
==> default:   File "/vagrant/source/apps/crawl_space/views.py", line 215, in get_object
==> default:     project=self.get_project(),
==> default:   File "/vagrant/source/apps/crawl_space/views.py", line 35, in get_project
==> default:     return Project.objects.get(slug=self.kwargs['project_slug'])
==> default:   File "/home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
==> default:     return getattr(self.get_queryset(), name)(*args, **kwargs)
==> default:   File "/home/vagrant/miniconda/envs/memex/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
==> default:     self.model._meta.object_name)
```

**Comment by ahmadia** [comment]
Thanks @lewismc - I'm not sure how the command is getting screwed up, but I'm digging into it.

**Comment by chrismattmann** [comment]
ACK

**Comment by chrismattmann** [comment]
in other news, scope out this GeoTopic identification for Tika! Woot. https://wiki.apache.org/tika/GeoTopicParser

**Comment by ahmadia** [comment]
Fixed in https://github.com/memex-explorer/memex-explorer/pull/532
