### ISSUE TITLE
Installing Memex Explorer stuck when python modules not found 

### ISSUE THREAD

**Issue by nipunhere** [memex-explorer/memex-explorer#611]
I followed the instructions as listed by @brittainhard . When I reach the step to hit -
celery -A memex worker -l info

Its showing an error - ImportError: No module named objects

_________________________________________________________________________________

For reference, as requested by Brittian - 
LMC-007877:source ndoshi$ source activate memex
discarding /Users/ndoshi/anaconda/bin from PATH
prepending /Users/ndoshi/anaconda/envs/memex/bin to PATH
(memex)LMC-007877:source ndoshi$ python --version
Python 2.7.8 :: Continuum Analytics, Inc.
(memex)LMC-007877:source ndoshi$ conda --version
conda 3.14.1
(memex)LMC-007877:source ndoshi$ pip --version
pip 7.1.0 from /Users/ndoshi/anaconda/envs/memex/lib/python2.7/site-packages (python 2.7)
(memex)LMC-007877:source ndoshi$ source deactivate memex
Error: too many arguments.
(memex)LMC-007877:source ndoshi$ source deactivate
discarding /Users/ndoshi/anaconda/envs/memex/bin from PATH
LMC-007877:source ndoshi$ python --version
Python 2.7.10 :: Anaconda 2.3.0 (x86_64)
LMC-007877:source ndoshi$ conda --version
conda 3.14.1
LMC-007877:source ndoshi$ pip --version
pip 7.1.0 from /Users/ndoshi/anaconda/lib/python2.7/site-packages (python 2.7)
LMC-007877:source ndoshi$ 
_________________________________________________________________________________

Command Line Trace -

LMC-007877:source ndoshi$ celery -A memex worker -l info
/Users/ndoshi/anaconda/lib/python2.7/site-packages/crispy_forms/utils.py:25: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.
  default_field_template = memoize(default_field_template, {}, 1)

Traceback (most recent call last):
  File "/Users/ndoshi/anaconda/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/fixups/django.py", line 73, in on_import_modules
    self.worker_fixup.validate_models()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/celery/fixups/django.py", line 158, in validate_models
    django_setup()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/debug_toolbar/settings.py", line 232, in patch_all
    patch_root_urlconf()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/debug_toolbar/settings.py", line 220, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 550, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 352, in app_dict
    self._populate()
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/ndoshi/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/apache-tomcat-7.0.62/webapps/memex-explorer/source/memex/urls.py", line 6, in <module>
    url(r'', include('base.urls', namespace="base")),
  File "/Users/ndoshi/anaconda/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/ndoshi/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/apache-tomcat-7.0.62/webapps/memex-explorer/source/base/urls.py", line 17, in <module>
    from base import views
  File "/usr/local/apache-tomcat-7.0.62/webapps/memex-explorer/source/base/views.py", line 28, in <module>
    from apps.crawl_space.views import ProjectObjectMixin
  File "/usr/local/apache-tomcat-7.0.62/webapps/memex-explorer/source/apps/crawl_space/views.py", line 27, in <module>
    from apps.crawl_space.viz.plot import AcheDashboard
  File "/usr/local/apache-tomcat-7.0.62/webapps/memex-explorer/source/apps/crawl_space/viz/plot.py", line 10, in <module>
    from harvest import Harvest
  File "/usr/local/apache-tomcat-7.0.62/webapps/memex-explorer/source/apps/crawl_space/viz/harvest.py", line 10, in <module>
    from bokeh.objects import HoverTool
ImportError: No module named objects

**Comment by brittainhard** [comment]
For some reason the conda envorinment is installing bokeh 0.9.0 instead of 0.7.0. Also it fails to install tld and elasticsearch.

**Comment by ahmadia** [comment]
@nipunhere - are you still hitting this error?

**Comment by brittainhard** [comment]
I think this was only on his machine. Very weird bug too. Could happen again.

**Comment by ahmadia** [comment]
If we can't reproduce, let's close.  Happy to reopen if it shows up again.

**Comment by ruba912** [comment]
i am getting the same error.
