### ISSUE TITLE
failing local build

### ISSUE THREAD

**Issue by bovard** [memex-explorer/memex-explorer#678]
When I run:

```
cd source
./app_setup.sh
```
it runs for a good long while and then I get the following error:

```
npm http GET https://registry.npmjs.org/is-property
npm http 200 https://registry.npmjs.org/is-property

> ws@0.4.32 install /anaconda/envs/memex/lib/node_modules/log.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.32 install /anaconda/envs/memex/lib/node_modules/log.io/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
/anaconda/envs/memex/bin/log.io-server -> /anaconda/envs/memex/lib/node_modules/log.io/bin/log.io-server
/anaconda/envs/memex/bin/log.io-harvester -> /anaconda/envs/memex/lib/node_modules/log.io/bin/log.io-harvester

> log.io@0.3.4 postinstall /anaconda/envs/memex/lib/node_modules/log.io
> cake ensure:configuration

Creating ~/.log.io/ for configuration files.
If this fails, run npm using a specific user: npm install -g log.io --user 'ubuntu'
log.io@0.3.4 /anaconda/envs/memex/lib/node_modules/log.io
├── backbone@0.9.10
├── underscore@1.4.4
├── coffee-script@1.4.0
├── jquery-browserify@1.8.1
├── winston@0.6.2 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, colors@0.6.2, async@0.1.22, pkginfo@0.2.3, request@2.9.203)
├── express@3.0.6 (methods@0.0.1, fresh@0.1.0, range-parser@0.0.4, cookie-signature@0.0.1, buffer-crc32@0.1.1, cookie@0.0.5, commander@0.6.1, mkdirp@0.3.3, debug@2.2.0, send@0.1.0, connect@2.7.2)
├── jquery@1.8.3 (navigator@1.0.1, location@0.0.1, xmlhttprequest@1.4.2, htmlparser@1.7.6, jsdom@0.2.19, contextify@0.1.14)
├── socket.io-client@0.9.17 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
└── socket.io@0.9.17 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "//anaconda/envs/memex/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/.../memex-explorer/source/memex/__init__.py", line 3, in <module>
    from .celery import app as celery_app
  File "/Users/.../memex-explorer/source/memex/celery.py", line 6, in <module>
    from celery import Celery
  File "//anaconda/envs/memex/lib/python2.7/site-packages/celery/__init__.py", line 130, in <module>
    from celery import five
  File "//anaconda/envs/memex/lib/python2.7/site-packages/celery/five.py", line 51, in <module>
    from kombu.five import monotonic
  File "//anaconda/envs/memex/lib/python2.7/site-packages/kombu/five.py", line 52, in <module>
    libSystem = ctypes.CDLL('libSystem.dylib')
  File "//anaconda/envs/memex/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libSystem.dylib, 6): image not found
~/Code/me/memex-explorer/deploy ~/Code/me/memex-explorer/source
~/Code/me/memex-explorer/source
discarding //anaconda/envs/memex/bin from PATH
source$
```

Looking through commands in `app_setup.sh` this looks like it is happening in the `python manage.py migrate` step:

```
source$ source activate memex
discarding //anaconda/bin from PATH
prepending //anaconda/envs/memex/bin to PATH
(memex)source$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "//anaconda/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "//anaconda/envs/memex/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/.../memex-explorer/source/memex/__init__.py", line 3, in <module>
    from .celery import app as celery_app
  File "/Users/.../memex-explorer/source/memex/celery.py", line 6, in <module>
    from celery import Celery
  File "//anaconda/envs/memex/lib/python2.7/site-packages/celery/__init__.py", line 130, in <module>
    from celery import five
  File "//anaconda/envs/memex/lib/python2.7/site-packages/celery/five.py", line 51, in <module>
    from kombu.five import monotonic
  File "//anaconda/envs/memex/lib/python2.7/site-packages/kombu/five.py", line 52, in <module>
    libSystem = ctypes.CDLL('libSystem.dylib')
  File "//anaconda/envs/memex/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libSystem.dylib, 6): image not found
(memex)LS2-00133:source bovardtiberi$
Traceback (most recent call last):
```

**Comment by ahmadia** [comment]
@bovard - sorry for the delay in responding to this.  It looks like there's a problem with your Anaconda install.

```
OSError: dlopen(libSystem.dylib, 6): image not found
```

9 times out of 10 these are caused when you have `DYLD_LIBRARY_PATH`, `LD_LIBRARY_PATH`, or `DYLD_FALLBACK_LIBRARY_PATH` defined in your environment.  You can check what's in your environment by typing `printenv` at your shell.

Also, I usually recommend that people install Anaconda into its default location in their home directory to avoid permissions issues.

Let me know if this helps.

**Comment by bovard** [comment]
@ahmadia thanks, I'll take a look later this week

**Comment by ahmadia** [comment]
@bovard - Any progress on this?

**Comment by bovard** [comment]
@ahmadia it works! just needed to do `export DYLD_FALLBACK_LIBRARY_PATH=/usr/lib`

**Comment by ahmadia** [comment]
```
export DYLD_FALLBACK_LIBRARY_PATH=/usr/lib
```

Was it set to something else before?  Setting `DYLD_FALLBACK_LIBRARY_PATH=/usr/lib` is going to cause problems for any user-installed tools (Homebrew, MacPorts, conda) in the future.

**Comment by bovard** [comment]
Looks like it was set to:
```
DYLD_FALLBACK_LIBRARY_PATH: :/Users/me/anaconda/lib:/Users/me/anaconda/lib
```

**Comment by bovard** [comment]
Looks like the crawl functionality doesn't work, displays JAVA_HOME is set to... and usage but doesn't do any crawling locally.

**Comment by ahmadia** [comment]
Yeah, try unsetting it completely.

**Comment by ahmadia** [comment]
Sorry, missed that last message from you.  `memex-explorer` is a web application, did you start it up using supervisor and then point your browser to localhost?
