### ISSUE TITLE
MultiValueKeyError Exception

### ISSUE THREAD

**Issue by saloneerege** [memex-explorer/memex-explorer#706]
Hello,
   When I try to create a new project and then add my URL seed list it throws an exception MultivalueKey error. If however on the other hand I first add the seed list and use it in a new project that I create it adds the URL list successfully.

**Comment by brittainhard** [comment]
Can you do me a favor and post the traceback?

**Comment by saloneerege** [comment]
Environment:


Request Method: POST
Request URL: http://localhost:8000/projects/crawling/

Django Version: 1.7.3
Python Version: 2.7.8
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'crispy_forms',
 'base',
 'task_manager',
 'rest_framework',
 'apps.crawl_space',
 'debug_toolbar')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/home/salonee/memex-explorer/source/base/views.py" in post
  108.         if request.POST["action"] == "index_status":
File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py" in __getitem__
  319.             raise MultiValueDictKeyError(repr(key))

Exception Type: MultiValueDictKeyError at /projects/crawling/
Exception Value: "'action'"

**Comment by brittainhard** [comment]
So I think that these errors are connected. Can you give me a step-by-step explanation of how this error comes about? As in, what buttons you pushed, what data you entered, etc.

Thanks for reporting these errors by the way, theres no other way we would discover them.

**Comment by saloneerege** [comment]
Hello, what I noticed is that if I first create a seed list and then create a project and include that already created seedlist everything works fine. But If I first create a new project and then add a new seed list it throws the multivalue key excpetion. This should not be happening. It should work either way right?

**Comment by brittainhard** [comment]
Yes, this shouldn't be happening. This line `if request.POST["action"] == "index_status":` gets the status of any indexes that have been created. It doesn't have anything to do with creating seeds lists. Moreover, this script is only loaded on the project overview page, so the error is somehow coming from that page.

**Comment by saloneerege** [comment]
I tried a variety of URLs like even facebook or google and the oones that I gave work fine when I try to create the seed list first and then the project. But if I first create a new project and then create a seed list it throws that exception.

**Comment by brittainhard** [comment]
How are you creating the seeds list. Are you doing it from the project page or the /seeds page?

**Comment by brittainhard** [comment]
Also, can you post the content of memex-explorer/source/memex/logs/debug.log ? That will probably help a lot.

**Comment by saloneerege** [comment]
I am first creating the seed list from the seed list page and only then creating a new project to add the previously created seedlist. That works. But the other way around does not work.

**Comment by saloneerege** [comment]
Internal Server Error: /projects/firstcrawl/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /projects/firstcrawl/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/firstcrawl/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Not Found: /bokehjs/static/js/vendor/font-awesome-4.2.0/fonts/fontawesome-webfont.woff
Not Found: /bokehjs/static/js/vendor/font-awesome-4.2.0/fonts/fontawesome-webfont.ttf
Not Found: /bokehjs/static/js/vendor/font-awesome-4.2.0/fonts/fontawesome-webfont.woff
Not Found: /bokehjs/static/js/vendor/font-awesome-4.2.0/fonts/fontawesome-webfont.ttf
Internal Server Error: /projects/crawling/
Traceback (most recent call last):
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/salonee/memex-explorer/source/base/views.py", line 108, in post
    if request.POST["action"] == "index_status":
  File "/home/salonee/miniconda3/envs/memex/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'action'"
Not Found: /favicon.ico




Contents of the debug.log

**Comment by brittainhard** [comment]
What browser are you using, by chance?

**Comment by saloneerege** [comment]
I'm using mozilla firefox. I have been using memex on ubuntu. Do you think the version of mozilla firefox make a difference to using memex explorer ?

**Comment by brittainhard** [comment]
I really don't know. I'm trying it in different browsers and not getting the error. Try opening the developer console in firefox and post any errors you might see there. I think that there may be some errors in one of the javascript files, maybe.

**Comment by ahmadia** [comment]
@brittainhard - Did any of your recent PRs address/fix this?

**Comment by brittainhard** [comment]
@ahmadia I was not able to replicate this bug, sadly. I know of a small fix that may fix it, but since I cant replicate it, I cant make sure that the fix is working.

**Comment by ahmadia** [comment]
@saloneerege - If you have time this week I'd like to chase this down.  Can you reproduce this with the latest version of Memex Explorer?  Let me know if you need help updating to the latest version.
