### ISSUE TITLE
New crawls stuck at "GENERATE"

### ISSUE THREAD

**Issue by brittainhard** [memex-explorer/memex-explorer#736]
If I start a crawl after another crawl has finished, it doesnt appear to be able to get past the generate phase. It just sticks.

**Comment by ahmadia** [comment]
That's bad news, let me see if I can reproduce.

**Comment by ahmadia** [comment]
Just ran two one-round crawls without visualization, so it's not an immediate problem with the REST API.

**Comment by brittainhard** [comment]
i'll try recreating the environment

**Comment by ahmadia** [comment]
I think I reproduced this.

**Comment by ahmadia** [comment]
I had to run two crawls simultaneously.  Did you run one after the other or two at the same time?

**Comment by brittainhard** [comment]
I just ran one after another. Waited till the first finished. Got a log for ya!

**Comment by ahmadia** [comment]
sure.

**Comment by ahmadia** [comment]
Perfect.  Found the issue:

```
[2015-10-28 15:26:02,225: ERROR/MainProcess] Task task_manager.crawl_tasks.nutch[d8b28858-7322-4299-8c53-e47b3b193f72] raised unexpected: KeyError(u'http://www.innocenceatlanta.org/2011/08/men/',)
Traceback (most recent call last):
  File "/Users/bhard/anaconda/envs/memex/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/bhard/anaconda/envs/memex/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/bhard/Documents/memex-explorer/source/task_manager/crawl_tasks.py", line 49, in nutch
    url_trails.handle_messages()
  File "/Users/bhard/Documents/memex-explorer/source/apps/crawl_space/viz/stream.py", line 110, in handle_messages
    self.parse_message(m)
  File "/Users/bhard/Documents/memex-explorer/source/apps/crawl_space/viz/stream.py", line 126, in parse_message
    self.closed_urls[url] = (self.open_urls[url], NutchUrlTrails.jtime_to_datetime(message["timestamp"]))
KeyError: u'http://www.example.com'
```

**Comment by ahmadia** [comment]
Basically, the viz client maintains an internal list of closed and open urls and isn't robust to messages crossing over from one crawl into the other.

**Comment by ahmadia** [comment]
I'll provide some protection in the client against that kind of thing happening.

**Comment by ahmadia** [comment]
issue fixed in https://github.com/memex-explorer/memex-explorer/commit/d6d6b3f702248564dba62801ad5e75a696403531

retested locally.

**Comment by ahmadia** [comment]
Brittain, reopen this if it isn't fixed for you.
