### ISSUE TITLE
memrex start up issue

### ISSUE THREAD

**Issue by aim4pole** [memex-explorer/memex-explorer#768]
After trial and error, I was able to get all dependencies needed. But when I run the script 
./app_setup.sh , it gives the following output. 
``` 
~/memex/memex-explorer/source (master)
$ ./app_setup.sh
~/memex/memex-explorer ~/memex/memex-explorer/source
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at c:\Users\mohammeda\Continuum\Anaconda3:
#
conda                     3.19.0                   py35_0
Fetching package metadata: ....
Solving package specifications: ....................
# All requested packages already installed.
# packages in environment at c:\Users\mohammeda\Continuum\Anaconda3:
#
conda-env                 2.4.5                    py35_0
Fetching package metadata: ..............
Error: No packages found in current win-64 channels matching: elasticsearch 1.6|1.6.0*
~/memex/memex-explorer/source
~/memex/memex-explorer/source/memex ~/memex/memex-explorer/source
./app_setup.sh: line 9: //cp: No such file or directory
~/memex/memex-explorer/source
./app_setup.sh: line 12: activate: No such file or directory
[30084]: Querying supervisor for state of external applications
[30084]: Supervisord not running or no applications are running
Setting enable stream viz to: FalseTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\Users\mohammeda\Continuum\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "c:\Users\mohammeda\Continuum\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "c:\Users\mohammeda\Continuum\Anaconda3\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\Users\mohammeda\Continuum\Anaconda3\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "c:\Users\mohammeda\Continuum\Anaconda3\lib\site-packages\django\apps\config.py", line 86, in create
    module = import_module(entry)
  File "c:\Users\mohammeda\Continuum\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'crispy_forms'
./app_setup.sh: line 15: deactivate: No such file or directory
```

**Comment by brittainhard** [comment]
Can you give me some info on your system? It looks like you are using windows, but something like Cygwin?

**Comment by britthard** [comment]
Support and development for this project has been suspended. We appreciate the help in clearing up these issues, and they will be solved when development is resumed.

Thanks.
