### ISSUE TITLE
app_setup Error    migrate part

### ISSUE THREAD

**Issue by MyraBaba** [memex-explorer/memex-explorer#772]
Hi I tried to install memex on ubuntu as the following error..

---

  Successfully uninstalled Django-1.9
(memex) saftas@ps01:/data/memex-explorer/source$ pip install django==1.7.3
Collecting django==1.7.3
  Using cached Django-1.7.3-py2.py3-none-any.whl
Installing collected packages: django
Successfully installed django-1.7.3
(memex) saftas@ps01:/data/memex-explorer/source$ python manage.py migrate;
[29522]: Querying supervisor for state of external applications
[29522]: Supervisord not running or no applications are running
Setting enable stream viz to: FalseTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/settings.py", line 242, in patch_all
    patch_middleware_classes()
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/settings.py", line 221, in patch_middleware_classes
    if not is_toolbar_middleware_installed():
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/settings.py", line 201, in is_toolbar_middleware_installed
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/middleware.py", line 16, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 151, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 145, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/data/anaconda3/envs/memex/lib/python2.7/site-packages/debug_toolbar/toolbar.py", line 122, in get_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.templates: "No module named engine"

---

I manually remove django 1.10 and install 1.7.3  at memex environment. Still has this error.

On the other hand is there any virtual machine that memex-explorer installed already to test ?

Thanks A Lot.

**Comment by jresch** [comment]
I'm having the same problem
